FROM node:14 
"# Set the working directory to /app" 
"WORKDIR /app" 
"# Copy the package*.json files to the working directory" 
"COPY package*.json ./ " 
"# Install the dependencies" 
"RUN npm install" 
"# Copy the rest of the application code to the working directory" 
"COPY . ." 
"# Expose the port that the application will run on" 
"EXPOSE 5678" 
"# Run the command to start the development server when the container launches" 
"CMD [\"npx\", \"n8n\", \"start\"]" 
